name: Upload Python Package

on:
  workflow_run:
    workflows: ["Tests"]
    types: [completed]

jobs:
  PyPi:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/fast-healthchecks
    permissions:
      contents: read
      id-token: write
    if: github.event.repository.fork == false && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Ensure run was for a tag
        run: git describe --tags --exact-match HEAD || exit 1

      - name: Install uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.12
        run: uv python install 3.12

      - name: Install the project
        run: uv sync --group=dev --group=docs --all-extras

      - name: Build the project
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e
